cache:
  directories:
    - $HOME/node_modules

language: node_js

script:
  - "npm test"
  - "npm run-script coverage"
  - "npm run-script lint"

node_js:
  - "node"

branches:
  only:
  - master

sudo: false